/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeautyShopsRouteImport } from './routes/beauty-shops'
import { Route as JewelryShopsRouteImport } from './routes/jewelry-shops'
import { Route as LiquorStoresRouteImport } from './routes/liquor-stores'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as SupermarketsRouteImport } from './routes/supermarkets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyShopsRoute = BeautyShopsRouteImport.update({
  id: '/beauty-shops',
  path: '/beauty-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelryShopsRoute = JewelryShopsRouteImport.update({
  id: '/jewelry-shops',
  path: '/jewelry-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquorStoresRoute = LiquorStoresRouteImport.update({
  id: '/liquor-stores',
  path: '/liquor-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SupermarketsRoute = SupermarketsRouteImport.update({
  id: '/supermarkets',
  path: '/supermarkets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beauty-shops': typeof BeautyShopsRoute
  '/jewelry-shops': typeof JewelryShopsRoute
  '/liquor-stores': typeof LiquorStoresRoute
  '/restaurants': typeof RestaurantsRoute
  '/supermarkets': typeof SupermarketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beauty-shops': typeof BeautyShopsRoute
  '/jewelry-shops': typeof JewelryShopsRoute
  '/liquor-stores': typeof LiquorStoresRoute
  '/restaurants': typeof RestaurantsRoute
  '/supermarkets': typeof SupermarketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beauty-shops': typeof BeautyShopsRoute
  '/jewelry-shops': typeof JewelryShopsRoute
  '/liquor-stores': typeof LiquorStoresRoute
  '/restaurants': typeof RestaurantsRoute
  '/supermarkets': typeof SupermarketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beauty-shops'
    | '/jewelry-shops'
    | '/liquor-stores'
    | '/restaurants'
    | '/supermarkets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beauty-shops'
    | '/jewelry-shops'
    | '/liquor-stores'
    | '/restaurants'
    | '/supermarkets'
  id:
    | '__root__'
    | '/'
    | '/beauty-shops'
    | '/jewelry-shops'
    | '/liquor-stores'
    | '/restaurants'
    | '/supermarkets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeautyShopsRoute: typeof BeautyShopsRoute
  JewelryShopsRoute: typeof JewelryShopsRoute
  LiquorStoresRoute: typeof LiquorStoresRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SupermarketsRoute: typeof SupermarketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-shops': {
      id: '/beauty-shops'
      path: '/beauty-shops'
      fullPath: '/beauty-shops'
      preLoaderRoute: typeof BeautyShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelry-shops': {
      id: '/jewelry-shops'
      path: '/jewelry-shops'
      fullPath: '/jewelry-shops'
      preLoaderRoute: typeof JewelryShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquor-stores': {
      id: '/liquor-stores'
      path: '/liquor-stores'
      fullPath: '/liquor-stores'
      preLoaderRoute: typeof LiquorStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supermarkets': {
      id: '/supermarkets'
      path: '/supermarkets'
      fullPath: '/supermarkets'
      preLoaderRoute: typeof SupermarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeautyShopsRoute: BeautyShopsRoute,
  JewelryShopsRoute: JewelryShopsRoute,
  LiquorStoresRoute: LiquorStoresRoute,
  RestaurantsRoute: RestaurantsRoute,
  SupermarketsRoute: SupermarketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
